/// @file tests/formatter/test_formatter_fixtures.cpp
///
/// @brief Fixture-driven round-trip tests for the formatter.
///
/// ─── What this file tests ─────────────────────────────────────────────────
/// Two test cases, one per fixture directory:
///
///   [fixtures][idempotent]  — for each `idempotent/*.lucid`, parse and
///                             format the source. Then parse and format
///                             the result. The two formatted texts must
///                             be identical. This is the idempotence
///                             requirement from Architecture.md §5.3.
///
///   [fixtures][canonical]   — for each `canonical/*.lucid`, parse and
///                             format the source. The result must match
///                             the sibling `*.expected` file byte for
///                             byte.
///
/// ─── Fixture layout ───────────────────────────────────────────────────────
/// tests/fixtures/formatter/
///   idempotent/
///     *.lucid                (sources; no expected output)
///   canonical/
///     *.lucid                (sources with non-canonical layout)
///     *.expected             (canonical output, generated by regen)
///
/// ─── Regeneration ─────────────────────────────────────────────────────────
/// When the formatter's layout changes, the canonical/*.expected files
/// need to be regenerated. Run:
///
///   cmake --build build --target regen-formatter-fixtures
///
/// Then `git diff tests/fixtures/formatter/canonical/` to review.

#include "formatter/Formatter.hpp"

#include <catch2/catch_test_macros.hpp>

#include <algorithm>
#include <filesystem>
#include <fstream>
#include <sstream>
#include <string>
#include <string_view>
#include <vector>

namespace fs = std::filesystem;

using lucid::formatter::format;
using lucid::formatter::FormatResult;

namespace
{

    constexpr std::string_view kFixtureDir = FIXTURE_DIR;

    std::string readFile(const fs::path &path)
    {
        std::ifstream in(path, std::ios::binary);
        if (!in)
            return {};
        std::ostringstream ss;
        ss << in.rdbuf();
        return ss.str();
    }

    std::vector<fs::path> collectByExtension(const fs::path &dir,
                                             std::string_view ext)
    {
        std::vector<fs::path> result;
        if (!fs::exists(dir))
            return result;
        for (const auto &entry : fs::directory_iterator(dir))
        {
            if (entry.is_regular_file() &&
                entry.path().extension() == ext)
            {
                result.push_back(entry.path());
            }
        }
        std::sort(result.begin(), result.end());
        return result;
    }

} // namespace

// ─────────────────────────────────────────────────────────────────────────────
// idempotent/ — format(format(x)) == format(x)
// ─────────────────────────────────────────────────────────────────────────────

TEST_CASE("fixtures/idempotent: formatting is idempotent",
          "[fixtures][idempotent]")
{
    const fs::path dir = fs::path(kFixtureDir) / "formatter" / "idempotent";
    const auto lucidFiles = collectByExtension(dir, ".lucid");

    if (lucidFiles.empty())
    {
        WARN("no fixtures found in " << dir);
        return;
    }

    for (const auto &lucidPath : lucidFiles)
    {
        const std::string fileName = lucidPath.filename().string();
        INFO("fixture: " << fileName);

        const std::string source = readFile(lucidPath);

        const FormatResult first = format(source, fileName);
        std::ostringstream diagnostics;
        for (const auto &diagnostic : first.diagnostics)
        {
            diagnostics << diagnostic.location.line() << ':'
                        << diagnostic.location.column() << ": "
                        << diagnostic.message << '\n';
        }
        INFO("diagnostics: " << diagnostics.str());
        REQUIRE(first.ok);
        INFO("first format produced: " << first.text);

        const FormatResult second = format(first.text, fileName);
        REQUIRE(second.ok);

        CHECK(first.text == second.text);
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// canonical/ — format(x) == expected
// ─────────────────────────────────────────────────────────────────────────────

TEST_CASE("fixtures/canonical: formatting matches the expected output",
          "[fixtures][canonical]")
{
    const fs::path dir = fs::path(kFixtureDir) / "formatter" / "canonical";
    const auto lucidFiles = collectByExtension(dir, ".lucid");

    if (lucidFiles.empty())
    {
        WARN("no fixtures found in " << dir);
        return;
    }

    for (const auto &lucidPath : lucidFiles)
    {
        const std::string fileName = lucidPath.filename().string();
        INFO("fixture: " << fileName);

        const std::string source = readFile(lucidPath);

        const FormatResult result = format(source, fileName);
        REQUIRE(result.ok);

        fs::path expectedPath = lucidPath;
        expectedPath.replace_extension(".expected");
        const std::string expected = readFile(expectedPath);

        if (expected.empty())
        {
            FAIL("missing or empty .expected file for " << fileName
                                                        << " — run `cmake --build build "
                                                           "--target regen-formatter-fixtures`");
            continue;
        }

        INFO("actual:   " << result.text);
        INFO("expected: " << expected);
        CHECK(result.text == expected);
    }
}