/// @file tests/parser/test_fixtures.cpp
///
/// @brief Fixture-driven tests for the parser and the dumper.
///
/// ─── What this file tests ─────────────────────────────────────────────────
/// Two test cases, one per fixture directory:
///
///   [fixtures][good]  — for each `good/*.lucid`, parse the file, dump
///                       the AST to JSON, and compare against the
///                       sibling `*.json`. The `.json` file is generated
///                       by the `regen-fixtures` target, never hand-
///                       edited.
///
///   [fixtures][bad]   — for each `bad/*.lucid`, parse the file and
///                       compare the diagnostic codes against the
///                       sibling `*.expected`. The `.expected` file is
///                       hand-maintained.
///
/// ─── Fixture layout ───────────────────────────────────────────────────────
/// tests/fixtures/parser/
///   good/
///     empty.lucid
///     empty.json            (generated by regen-fixtures)
///     import.lucid
///     import.json
///     ...
///   bad/
///     missing-name.lucid
///     missing-name.expected (hand-written, one DiagCode per line)
///     ...
///
/// ─── Regeneration ─────────────────────────────────────────────────────────
/// When the parser or the dumper changes, the good/*.json files may need
/// to be regenerated. Run:
///
///   cmake --build build --target regen-fixtures
///
/// Then `git diff tests/fixtures/parser/good/` to review the changes.

#include "core/diagnostics/Diagnostic.hpp"
#include "core/memory/ASTArena.hpp"
#include "core/memory/StringPool.hpp"
#include "parser/Parser.hpp"
#include "parser/context/ParserContext.hpp"
#include "parser/context/TokenStream.hpp"
#include "parser/dump/JSONDumper.hpp"

#include <catch2/catch_test_macros.hpp>

#include <algorithm>
#include <filesystem>
#include <fstream>
#include <sstream>
#include <string>
#include <string_view>
#include <utility>
#include <vector>

namespace fs = std::filesystem;

using lucid::diag::DiagCode;
using lucid::diag::DiagnosticEngine;
using lucid::parser::parseFile;
using lucid::parser::ParserContext;
using lucid::parser::TokenStream;
using lucid::parser::dump::dumpModule;

namespace
{

    constexpr std::string_view kFixtureDir = FIXTURE_DIR;

    std::string readFile(const fs::path &path)
    {
        std::ifstream in(path, std::ios::binary);
        if (!in)
            return {};
        std::ostringstream ss;
        ss << in.rdbuf();
        return ss.str();
    }

    std::vector<fs::path> collectByExtension(const fs::path &dir,
                                             std::string_view ext)
    {
        std::vector<fs::path> result;
        if (!fs::exists(dir))
            return result;
        for (const auto &entry : fs::directory_iterator(dir))
        {
            if (entry.is_regular_file() &&
                entry.path().extension() == ext)
            {
                result.push_back(entry.path());
            }
        }
        std::sort(result.begin(), result.end());
        return result;
    }

    // Parse a source and return the JSON dump of the module.
    std::string parseAndDump(const std::string &fileName,
                             const std::string &source)
    {
        StringPool pool;
        ASTArena arena;
        DiagnosticEngine diag(&pool);
        TokenStream stream(std::vector<Token>{
            Token{TokenType::EOF_TOKEN, InternedString{},
                  SourceLocation{1, 1}}});
        ParserContext ctx(pool, arena, diag, stream);

        ModuleAST *module = parseFile(fileName, source, ctx);
        return dumpModule(module, pool);
    }

    // Map a DiagCode to its enumerator name. The test's .expected files
    // use the enumerator names, not the numeric codes.
    std::string codeToString(DiagCode code)
    {
        switch (code)
        {
        case DiagCode::Syntax_ExpectedIdentifier:
            return "Syntax_ExpectedIdentifier";
        case DiagCode::Syntax_ExpectedToken:
            return "Syntax_ExpectedToken";
        case DiagCode::Syntax_UnexpectedToken:
            return "Syntax_UnexpectedToken";
        case DiagCode::Syntax_ExpectedLiteral:
            return "Syntax_ExpectedLiteral";
        case DiagCode::Syntax_ExpectedBlock:
            return "Syntax_ExpectedBlock";
        case DiagCode::Syntax_ExpectedClosing:
            return "Syntax_ExpectedClosing";
        case DiagCode::Syntax_IncompleteDeclaration:
            return "Syntax_IncompleteDeclaration";
        case DiagCode::Syntax_ExpectedModulePath:
            return "Syntax_ExpectedModulePath";
        case DiagCode::Syntax_ExpectedImportAlias:
            return "Syntax_ExpectedImportAlias";
        case DiagCode::Syntax_ExpectedEnumName:
            return "Syntax_ExpectedEnumName";
        case DiagCode::Syntax_ExpectedEnumBody:
            return "Syntax_ExpectedEnumBody";
        case DiagCode::Syntax_ExpectedEnumMember:
            return "Syntax_ExpectedEnumMember";
        case DiagCode::Syntax_ExpectedResourceName:
            return "Syntax_ExpectedResourceName";
        case DiagCode::Syntax_ExpectedResourceBody:
            return "Syntax_ExpectedResourceBody";
        case DiagCode::Syntax_ExpectedFieldName:
            return "Syntax_ExpectedFieldName";
        case DiagCode::Syntax_ExpectedFieldType:
            return "Syntax_ExpectedFieldType";
        case DiagCode::Syntax_ExpectedFieldDefault:
            return "Syntax_ExpectedFieldDefault";
        case DiagCode::Syntax_ExpectedNodeName:
            return "Syntax_ExpectedNodeName";
        case DiagCode::Syntax_ExpectedNodeExpr:
            return "Syntax_ExpectedNodeExpr";
        case DiagCode::Syntax_ExpectedNodeType:
            return "Syntax_ExpectedNodeType";
        case DiagCode::Syntax_ExpectedNodeArgList:
            return "Syntax_ExpectedNodeArgList";
        case DiagCode::Syntax_ExpectedTriggerList:
            return "Syntax_ExpectedTriggerList";
        case DiagCode::Syntax_ExpectedCompositeName:
            return "Syntax_ExpectedCompositeName";
        case DiagCode::Syntax_ExpectedCompositeBody:
            return "Syntax_ExpectedCompositeBody";
        case DiagCode::Syntax_ExpectedInputBlock:
            return "Syntax_ExpectedInputBlock";
        case DiagCode::Syntax_ExpectedOutputBlock:
            return "Syntax_ExpectedOutputBlock";
        case DiagCode::Syntax_ExpectedInputField:
            return "Syntax_ExpectedInputField";
        case DiagCode::Syntax_ExpectedOutputField:
            return "Syntax_ExpectedOutputField";
        case DiagCode::Syntax_ExpectedOutputBinding:
            return "Syntax_ExpectedOutputBinding";
        case DiagCode::Syntax_ExpectedValue:
            return "Syntax_ExpectedValue";
        case DiagCode::Syntax_ExpectedFieldAccess:
            return "Syntax_ExpectedFieldAccess";
        case DiagCode::Syntax_ExpectedAttributeName:
            return "Syntax_ExpectedAttributeName";
        case DiagCode::Syntax_ExpectedDeclaration:
            return "Syntax_ExpectedDeclaration";
        case DiagCode::Internal_Assertion:
            return "Internal_Assertion";
        case DiagCode::Internal_NotImplemented:
            return "Internal_NotImplemented";
        default:
            return "Other";
        }
    }

    // Parse a source and return the sequence of diagnostic codes,
    // in the order they were reported.
    std::vector<std::string> parseAndCollectCodes(const std::string &fileName,
                                                  const std::string &source)
    {
        StringPool pool;
        ASTArena arena;
        DiagnosticEngine diag(&pool);
        TokenStream stream(std::vector<Token>{
            Token{TokenType::EOF_TOKEN, InternedString{},
                  SourceLocation{1, 1}}});
        ParserContext ctx(pool, arena, diag, stream);

        (void)parseFile(fileName, source, ctx);

        std::vector<std::string> codes;
        for (const auto &d : diag.all())
        {
            codes.push_back(codeToString(d.code));
        }
        return codes;
    }

    // Read the expected codes from a `.expected` file: one code per
    // line, blank lines and lines starting with `#` ignored.
    std::vector<std::string> readExpectedCodes(const fs::path &path)
    {
        std::vector<std::string> codes;
        std::ifstream in(path);
        std::string line;
        while (std::getline(in, line))
        {
            // Trim trailing whitespace and CR (for files edited on
            // Windows).
            while (!line.empty() &&
                   (line.back() == '\r' || line.back() == ' '))
            {
                line.pop_back();
            }
            if (line.empty())
                continue;
            if (line.front() == '#')
                continue;
            codes.push_back(line);
        }
        return codes;
    }

} // namespace

// ─────────────────────────────────────────────────────────────────────────────
// good/ — parse, dump, compare against the stored JSON
// ─────────────────────────────────────────────────────────────────────────────

TEST_CASE("fixtures/good: parse and dump match stored JSON",
          "[fixtures][good]")
{
    const fs::path dir = fs::path(kFixtureDir) / "parser" / "good";
    const auto lucidFiles = collectByExtension(dir, ".lucid");

    if (lucidFiles.empty())
    {
        WARN("no fixtures found in " << dir);
        return;
    }

    for (const auto &lucidPath : lucidFiles)
    {
        const std::string fileName = lucidPath.filename().string();
        INFO("fixture: " << fileName);

        const std::string source = readFile(lucidPath);
        const std::string actual = parseAndDump(fileName, source);

        fs::path jsonPath = lucidPath;
        jsonPath.replace_extension(".json");
        const std::string expected = readFile(jsonPath);

        if (expected.empty())
        {
            FAIL("missing or empty .json file for " << fileName
                 << " — run `cmake --build build --target regen-fixtures`");
            continue;
        }
        CHECK(actual == expected);
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// bad/ — parse, collect codes, compare against the stored list
// ─────────────────────────────────────────────────────────────────────────────

TEST_CASE("fixtures/bad: parse produces the expected diagnostic codes",
          "[fixtures][bad]")
{
    const fs::path dir = fs::path(kFixtureDir) / "parser" / "bad";
    const auto lucidFiles = collectByExtension(dir, ".lucid");

    if (lucidFiles.empty())
    {
        WARN("no fixtures found in " << dir);
        return;
    }

    for (const auto &lucidPath : lucidFiles)
    {
        const std::string fileName = lucidPath.filename().string();
        INFO("fixture: " << fileName);

        const std::string source = readFile(lucidPath);
        const auto actual = parseAndCollectCodes(fileName, source);

        fs::path expectedPath = lucidPath;
        expectedPath.replace_extension(".expected");
        const auto expected = readExpectedCodes(expectedPath);

        REQUIRE_FALSE(expected.empty());

        INFO("actual codes:   " << [&]
             { 
            std::string s; for (auto& c : actual) { s += c; s += ' '; } return s; }());
        INFO("expected codes: " << [&]
             { 
            std::string s; for (auto& c : expected) { s += c; s += ' '; } return s; }());

        CHECK(actual == expected);
    }
}