/// @file tests/sema/test_sema_fixtures.cpp
///
/// @brief Fixture-driven end-to-end tests for Sema.
///
/// ─── What this tests ──────────────────────────────────────────────────────
/// Each fixture is a directory containing:
///
///   input.lucid           the root module's source
///   <name>.lucid          one or more additional modules
///   expected.json         the expected dumpGraph output
///
/// The test compiles input.lucid with a module loader that reads the
/// sibling .lucid files. If the compile succeeds, the resulting graph
/// is dumped to JSON and compared against expected.json.
///
/// ─── Directory layout ─────────────────────────────────────────────────────
/// tests/fixtures/sema/
///   hello/
///     input.lucid
///     expected.json
///   with-import/
///     input.lucid
///     keys.lucid
///     expected.json
///   ...
///
/// ─── Regeneration ─────────────────────────────────────────────────────────
/// The expected.json files are generated by the regen-fixtures tool.
/// They are never hand-written. Run:
///
///   cmake --build build --target regen-fixtures
///
/// and review the diff.

#include "SemaFixtureCommon.hpp"

#include <catch2/catch_test_macros.hpp>

#include <algorithm>
#include <filesystem>
#include <vector>

namespace fs = std::filesystem;

// ─────────────────────────────────────────────────────────────────────────────
// Fixture test
// ─────────────────────────────────────────────────────────────────────────────

TEST_CASE("fixtures/sema: compile and dump match expected JSON",
          "[fixtures][sema]")
{
    const fs::path root =
        fs::path(FIXTURE_DIR) / "sema";

    REQUIRE(fs::exists(root));

    // Collect fixture directories (subdirectories with an input.lucid).
    std::vector<fs::path> dirs;
    for (const auto &entry : fs::directory_iterator(root))
    {
        if (!entry.is_directory())
            continue;
        if (!fs::exists(entry.path() / "input.lucid"))
            continue;
        dirs.push_back(entry.path());
    }
    std::sort(dirs.begin(), dirs.end());

    REQUIRE_FALSE(dirs.empty());

    lucid::tests::sema_fixtures::FixtureRegistry reg;

    for (const fs::path &dir : dirs)
    {
        const std::string name = dir.filename().string();
        INFO("fixture: " << name);

        auto data = lucid::tests::sema_fixtures::loadFixture(dir);
        const std::string actual =
            lucid::tests::sema_fixtures::compileAndDump(data, reg.registry);

        if (actual.empty())
        {
            FAIL("fixture did not compile: " << name);
            continue;
        }

        const std::string expected =
            lucid::tests::sema_fixtures::readFile(dir / "expected.json");
        if (expected.empty())
        {
            FAIL("missing expected.json for fixture: " << name
                                                       << " — run `cmake --build build "
                                                          "--target regen-fixtures`");
            continue;
        }

        CHECK(actual == expected);
    }
}